version: '3.8'

services:
  mariadb:
    image: mariadb:11.8
    container_name: task-management-mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: SuperSecret123
      MYSQL_DATABASE: task_management_dev
      MYSQL_USER: app_user
      MYSQL_PASSWORD: SuperSecret123
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

volumes:
  mariadb_data: 