services:
  mariadb:
    image: mariadb:11.1
    container_name: task-management-mariadb
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: rootpassword
      MARIADB_DATABASE: task_management
      MARIADB_USER: taskuser
      MARIADB_PASSWORD: taskpassword
      MARIADB_CHARACTER_SET_SERVER: utf8mb4
      MARIADB_COLLATE_SERVER: utf8mb4_unicode_ci
    ports:
      - "3307:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./docker/mariadb/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - task-management
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3

  # Optional: phpMyAdmin for database management
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2
    container_name: task-management-phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
      PMA_USER: taskuser
      PMA_PASSWORD: taskpassword
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "8081:80"
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - task-management

volumes:
  mariadb_data:
    driver: local

networks:
  task-management:
    driver: bridge 