spring:
  # JPA Configuration for MariaDB Docker (Development/Testing)
  datasource:
    url: jdbc:mariadb://localhost:3306/task_management_dev
    username: root
    password: SuperSecret123
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 20  # Smaller pool for development
      minimum-idle: 5
      idle-timeout: 300000
      max-lifetime: 1200000

  # JPA/Hibernate Configuration for MariaDB Development
  jpa:
    hibernate:
      ddl-auto: update  # Keep tables and data between restarts
    show-sql: true  # Show SQL queries for debugging
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true
        jdbc:
          time_zone: UTC

  # Disable SQL initialization - let JPA handle table creation
  sql:
    init:
      mode: never

# Logging Configuration for MariaDB Development
logging:
  level:
    com.example.springhttpclientdatajpademo: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.jdbc.core: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Application Configuration for Development
app:
  # Background processor settings
  background-processor:
    check-interval-ms: 30000  # Check for queued tasks every 30 seconds
    
  # Mock External Services Configuration for Development
  mock:
    glean:
      enabled: true
      min-delay-ms: 800
      max-delay-ms: 2500
      failure-rate: 0.1
      simulate-timeouts: true
      smart-answers: true
      citation-count: 3
    llm:
      enabled: true
      min-delay-ms: 300
      max-delay-ms: 1000
      failure-rate: 0.05
      intelligent-similarity: true
      identical-text-similarity: 0.95
      min-random-similarity: 0.3
      max-random-similarity: 0.9 