spring:
  datasource:
    url: jdbc:mariadb://localhost:3307/task_management?useUnicode=true&characterEncoding=utf8mb4&useSSL=false&allowPublicKeyRetrieval=true
    username: taskuser
    password: taskpassword
    driver-class-name: org.mariadb.jdbc.Driver
    
    # Connection pool configuration (HikariCP)
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1200000
      leak-detection-threshold: 60000
      pool-name: TaskManagementHikariPool

  jpa:
    database: MYSQL
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update  # Use 'update' for development, 'validate' for production
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true
        use_sql_comments: true
        jdbc:
          batch_size: 20
          batch_versioned_data: true
        order_inserts: true
        order_updates: true
        connection:
          charset: utf8mb4
        temp:
          use_jdbc_metadata_defaults: false
    show-sql: true

  # SQL initialization (disabled since we use JPA auto-generation)
  sql:
    init:
      mode: never

# Application configuration
app:
  database:
    type: mariadb
    charset: utf8mb4

# Logging configuration for MariaDB
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.mariadb.jdbc: DEBUG
    com.example.springhttpclientdatajpademo: DEBUG
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss}){faint} %clr(%5p) %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} : %m%n%wEx"

# Management endpoints (same as dev profile)
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always 