spring:
  # Production-specific overrides
  jpa:
    hibernate:
      ddl-auto: validate  # Strict validation in production
    show-sql: false       # Never show SQL in production
  
  # Production logging
  logging:
    level:
      com.example.springhttpclientdatajpademo: INFO
      org.springframework.web: WARN
      org.hibernate.SQL: WARN
      org.hibernate.type.descriptor.sql.BasicBinder: WARN
      org.springframework.web.cors: WARN
    pattern:
      console: "%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} - %msg%n"

# Production-specific settings
app:
  file:
    max-size: 52428800  # 50MB in production (smaller than dev)
  excel:
    max-sheets: 5       # More restrictive in production
    max-rows-per-sheet: 5000
  # Production CORS - Restrictive for security
  cors:
    allowed-origins:
      - https://evaluation-app.organization.com
      - https://evaluation-portal.organization.com
    allowed-methods:
      - GET
      - POST
      - PUT
      - DELETE
      - OPTIONS
    max-age: 3600  # 1 hour for production 