spring:
  # JPA Configuration for MariaDB Kubernetes (Development/Testing)
  datasource:
    url: jdbc:mariadb://localhost:3306/task_management_dev
    username: root
    password: rootpassword
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 20  # Smaller pool for development
      minimum-idle: 5
      idle-timeout: 300000
      max-lifetime: 1200000

  # JPA/Hibernate Configuration for MariaDB Development
  jpa:
    hibernate:
      ddl-auto: create-drop  # Temporarily recreate tables to show clean DDL
    show-sql: true  # Show SQL queries for debugging
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true
        globally_quoted_identifiers: false  # Disable automatic identifier quoting for cleaner DDL
        jdbc:
          time_zone: UTC

  # Disable SQL initialization - let JPA handle table creation
  sql:
    init:
      mode: never

# Logging Configuration for MariaDB Development
logging:
  level:
    com.example.springhttpclientdatajpademo: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.jdbc.core: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n" 