spring:
  # JPA Configuration for H2 (Development only)
  datasource:
    url: jdbc:h2:file:./data/task_management_h2;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
    driver-class-name: org.h2.Driver

  # JPA/Hibernate Configuration for H2
  jpa:
    hibernate:
      ddl-auto: update  # Keep tables and data between restarts
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true

  # Explicitly disable SQL initialization to prevent schema-h2.sql issues
  sql:
    init:
      mode: never

  # H2 Console (for debugging)
  h2:
    console:
      enabled: true
      path: /h2-console

# Logging Configuration for Development
logging:
  level:
    com.example.springhttpclientdatajpademo: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n" 