spring:
  threads:
    virtual:
      enabled: true

  application:
    name: task-management-api
  profiles:
    active: mariadb
  
  # JPA Configuration for MariaDB
  datasource:
    url: jdbc:mariadb://localhost:3306/task_management
    username: taskuser
    password: taskpassword
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 50
      minimum-idle: 10
      idle-timeout: 300000
      max-lifetime: 1200000

  # JPA/Hibernate Configuration
  jpa:
    hibernate:
      ddl-auto: update  # Let Hibernate manage tables (use 'update' for production)
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true
        jdbc:
          time_zone: UTC

  # File Upload Configuration
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true

  # Jackson Configuration
  jackson:
    default-property-inclusion: NON_NULL
    time-zone: UTC
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSS'Z'

# Logging Configuration
logging:
  level:
    com.example.springhttpclientdatajpademo: INFO
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# Server Configuration
server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

# Management/Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

# Application-specific Configuration
app:
  file:
    max-size: 104857600  # 100MB in bytes
    allowed-types: .xlsx,.xls
  excel:
    max-sheets: 10
    max-rows-per-sheet: 10000
  jwt:
    # JWT configuration would go here in real implementation
    issuer: internal-sso-server
  name: Internal Task Management API
  version: 1.0.0
  
  # Task Types Configuration
  task-types:
    enabled:
      - chat-evaluation
      - url-cleaning
      # - search-evaluation  # Disabled for now
      # - qna-preparation    # Disabled for now
    
    settings:
      chat-evaluation:
        display-name: "Chat Evaluation"
        description: "Evaluate chat responses against golden answers using LLM similarity"
        max-file-size-mb: 50
        max-rows-per-sheet: 1000
        required-columns:
          - question
          - golden_answer
          - golden_citations
        parser-service-bean: "chatEvaluationExcelParsingService"
        background-processing: true
        estimated-time-per-row-seconds: 2.0
      
      url-cleaning:
        display-name: "URL Cleaning"
        description: "Clean and validate URLs from Excel files"
        max-file-size-mb: 25
        max-rows-per-sheet: 5000
        required-columns:
          - url
        parser-service-bean: "urlCleaningExcelParsingService"
        background-processing: true
        estimated-time-per-row-seconds: 0.5
      
      search-evaluation:
        display-name: "Search Evaluation"
        description: "Evaluate search results quality and relevance"
        max-file-size-mb: 30
        max-rows-per-sheet: 2000
        required-columns:
          - query
          - expected_results
        parser-service-bean: "searchEvaluationExcelParsingService"
        background-processing: true
        estimated-time-per-row-seconds: 1.5
  
  # CORS Configuration
  cors:
    allowed-origins: 
      - http://localhost:3000
      - http://localhost:3001
      - http://localhost:4200
    allowed-methods:
      - GET
      - POST
      - PUT
      - DELETE
      - OPTIONS
    max-age: 3600 